### ISSUE TITLE
Not able to generate html report

### ISSUE THREAD

**Issue by jasminpethani** [fromkk/TestSummaries#5]
I have followed steps you have mention to generate html report. My requirement is to  generate sample report telling which test cases are failed or succeed with number of testcases which are failed or succeeded 

Tried Command: 
`test-summaries --resultDirectory . --outputPath ~/Desktop/report.html --outputType HTML`

 Html report generated 
![screen shot 2018-12-26 at 12 05 15 pm](https://user-images.githubusercontent.com/4652669/50435301-a5586c00-0906-11e9-8eee-3e816db67d0c.png)

I want report in following html form
![screen shot 2018-12-26 at 12 10 20 pm](https://user-images.githubusercontent.com/4652669/50435446-57903380-0907-11e9-8ffd-d9116862d24a.png)

Help me what to do ?

**Comment by fromkk** [comment]
@jasminpethani Thank you for using `TestSummaries`.
Sorry, this tool is generate list of screenshots HTML or PNG images with UITest.
I may not be able to fulfill what you wanted.

**Comment by jasminpethani** [comment]
@fromkk  Thanks for reply. you can close this issue

**Comment by fromkk** [comment]
@jasminpethani thank you!
